# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eiordach <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/09/27 21:02:25 by eiordach          #+#    #+#              #
#    Updated: 2017/09/27 21:21:40 by eiordach         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat

OBJ = main.o

SRC = main.c

alL	:	
		gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)
		#gcc -o $(NAME)

clean :
		/bin/rm -f $(OBJ)

fclean : clean
		/bin/rm -f $(NAME)
